### ISSUE TITLE
Add json and yaml lint tasks.

### ISSUE THREAD

**Issue by guncha25** [wunderio/code-quality#14]
Since all projects use yaml and json files we need to lint them also.

**Comment by hkirsman** [comment]
There's yamllint and jsonlint in GrumpPHP. Did you mean we should enable these?

**Comment by guncha25** [comment]
We should add custom tasks so that file finder works better. For example json linter currently runs only on .json files. but .lock files should also be tested (for error in merge conflict resolution)
