### ISSUE TITLE
Add ignore lists

### ISSUE THREAD

**Issue by tormi** [wunderio/code-quality#17]
Some files are invalid on purpose (for testing). How to deal with them?

```
lando grum --tasks yaml_lint
GrumPHP is sniffing your code!
Running task 1/1: YamlLintTask... ✘
[ERROR] Indentation problem in "./web/core/tests/Drupal/Tests/Core/Asset/library_test_files/invalid_file.libraries.yml" at line 3 (near "  key2: value2").
```

**Comment by tormi** [comment]
For `phpcs` I can probably use `ignore_patterns`. What about other tasks?

```
    phpcs:
      ignore_patterns:
        - ./web/core/tests/
```

**Comment by guncha25** [comment]
ignore_patterns can be defined for every task in this package. Although i must admit that there should be link to each tasks readme in main readme.
