### ISSUE TITLE
There should not be +x permission on config/grumphp.yml

### ISSUE THREAD

**Issue by hkirsman** [wunderio/code-quality#29]
I think the correct permission should be 644 or is there any reason it has executable permission?

**Comment by marekfilip** [comment]
Hi! I'd like to help but I wonder, if correct permissions maybe it should be done for all files not only 
`config/grumphp.yml`? I propose to change all files permissions to 644, all folders to 755, except `bin/check_perms` which should have 755 i guess?

**Comment by marekfilip** [comment]
So I changed permissions only for this one file. If my [proposal](https://github.com/wunderio/code-quality/issues/29#issuecomment-536695679) to fix permissions on other files make sense, I can do that as well. Check out the #30.
