### ISSUE TITLE
Javascript files not being scanned by phpcs

### ISSUE THREAD

**Issue by hkirsman** [wunderio/code-quality#75]
Deivids Briedis discovered that deploy is complaining about issues in javascript files but running grumphp locally there are no errors.

It seems that the issue is that we've not added js as allowed extension for phpcs https://github.com/wunderio/code-quality/blob/master/src/Task/tasks.yml#L126

Should we change that?

**Comment by misterjoonas** [comment]
Is phpcs supposed to check JS files? The validation errors are all about:
`TRUE, FALSE and NULL must be uppercase; expected "TRUE" but found "true" (Generic.PHP.UpperCaseConstant.Found)`
but lowercase is used for boolean values in JS.

**Comment by hkirsman** [comment]
Indeed, and TRUE is not even proper javascript. So this means we don't want to add js as default extension.

What I don't understand is how during deploy js files are scanned? Was it just a glitch?

@deiviic @misterjoonas

**Comment by deiviic** [comment]
@hkirsman Yes, it seems I missed the config when I initially investigated this but it's been fixed. I'm not sure why this issue didn't show up locally when running GrumPHP but only when running PHPCS separately.

https://github.com/wunderio/client-fi-lab-elab/commit/4e9a635adbd67c70a5918e946d1f356e9e95aeaf

**Comment by hkirsman** [comment]
Maybe you didn't use GrumpPHP and bypassed some of our default configs? With GrumPHP one can run specific task like this:

    ./vendor/bin/grumphp run --tasks=phpcs

**Comment by deiviic** [comment]
I just ran
`lando grumphp run`
and then found the issue when running phpcs independently of GrumPHP. Perhaps in that case some configs were bypassed but I remember using the `phpcs.xml` as the standard and it's also used in GrumPHP. In any case, the JS file exclusion was missing from the `phpcs.xml` file and now it's fixed. 🙂

**Comment by hkirsman** [comment]
Ok, thanks. 

I'll close this and create something new instead - adding ESLint to lint Drupal js with Drupal rules #84
