### ISSUE TITLE
Version 2.2.2 is not compatible with Drupal 10 due to symfony/finder version

### ISSUE THREAD

**Issue by alexdrupal** [wunderio/code-quality#91]
`composer require --dev wunderio/code-quality ^2.2.2 -W`

> Problem 1
    - Root composer.json requires wunderio/code-quality ^2.2.2 -> satisfiable by wunderio/code-quality[2.2.2].
    - wunderio/code-quality 2.2.2 requires symfony/finder ^4.4 -> found symfony/finder[v4.4.0-BETA1, ..., 4.4.x-dev] but these were not loaded, likely because it conflicts with another require.

**Comment by hkirsman** [comment]
Merged and created new release.
